Add consent functionality
niamh-d/qa_auto_hw_w3 pull request #4
Opened 2024-10-04 15:07 UTC by niamh-d

Added following two new methods to Processor class:
- revokeConsent
- verifyConsent 

 Added relevant unit tests

2024-10-05 06:30 UTC, vladimir-tl commented on test/Processer.test.ts
> +      processor.giveConsent(user)
general comment: test name too long, we don't have to describe all steps just main idea

2024-10-05 06:30 UTC, vladimir-tl commented on src/Processor.ts
> +
pls delety empty lines here and other places

2024-10-05 06:33 UTC, vladimir-tl requested changes
general: Consider adding more descriptive commit messages for better traceability of changes.

2024-10-06 10:27 UTC, niamh-d commented on test/Processer.test.ts
> +      processor.giveConsent(user)
done

2024-10-06 10:28 UTC, niamh-d commented on src/Processor.ts
> +
done

2024-10-06 10:29 UTC, merged